### ISSUE TITLE
(Feature Request) Obtain Hex (cell) co-ordinates

### ISSUE THREAD

**Issue by shinyone** [ksemianov/HexGrid#1]
Having rendered the "Hexes" I would like to add things on top, it would be great if the hex vertices were stored during or after layout and could be retrievable.

If there was an array property on the cell data could the 6 CGPoints be populated so the cell has this information?  With 0 index being top,left vertex, going around clockwise.

P.S. Thanks for sharing it has made it quicker to start my project.

**Comment by ksemianov** [comment]
Hi! Thanks for the question.

Exposing exact coordinates for SwiftUI layout containers is not a common practice. You won't find coordinates of subviews in `HStack` or `VStack`. Can you share a bit more on what you are trying to accomplish?

You can already "add things on top" by modifying cell views. Here is a more elaborate example:

<img width="873" alt="image-example" src="https://github.com/ksemianov/HexGrid/assets/18328341/4b1f5aea-d54a-41a3-b4b5-4c45c4dfd99a">

```swift
struct CellModel: Identifiable, OffsetCoordinateProviding {
    var id: Int { offsetCoordinate.hashValue }
    var offsetCoordinate: OffsetCoordinate
    var name: String
    var imageUrl: URL
}

struct CellView: View {
    var name: String
    var imageUrl: URL

    var body: some View {
        Text(name)
            .padding(8)
            .background(Color.gray)
            .clipShape(RoundedRectangle(cornerRadius: 16))
            .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .bottom)
            .padding(.bottom, 8)
            .background {
                AsyncImage(url: imageUrl) { image in
                    image.resizable().aspectRatio(contentMode: .fill)
                } placeholder: {
                    ProgressView().frame(maxWidth: .infinity, maxHeight: .infinity)
                }
            }
    }
}

struct ContentView: View {
    let cells: [CellModel] = [
        .init(offsetCoordinate: .init(row: 0, col: 0), name: "Ash", imageUrl: URL(string: "https://cataas.com/cat")!),
        .init(offsetCoordinate: .init(row: 0, col: 1), name: "Twics", imageUrl: URL(string: "https://cataas.com/cat")!),
        .init(offsetCoordinate: .init(row: 0, col: 2), name: "Panther", imageUrl: URL(string: "https://cataas.com/cat")!),
        .init(offsetCoordinate: .init(row: 1, col: 0), name: "Olive", imageUrl: URL(string: "https://cataas.com/cat")!),
        .init(offsetCoordinate: .init(row: 1, col: 1), name: "Blackie", imageUrl: URL(string: "https://cataas.com/cat")!)
    ]

    var body: some View {
        HexGrid(cells) { cell in
            CellView(name: cell.name, imageUrl: cell.imageUrl)
        }
        .padding()
    }
}
```

**Comment by shinyone** [comment]
OK, Thanks for the quick reply.
That's actually very helpful but doesn't answer my question which was perhaps badly explained.

I would like to overlay more graphic objects over the whole HexGrid not within a HexCell.
For example, adding a star on a specific hex corner or text written over an edge at the same angle.  It needs to be displayed on top.

if HexGrid frame is the bottom layer (view) I need positional information in order to .offset or  .position objects on the layer (view) above.

If I had the path information for each hex I would know where the corners and edges were.   But perhaps this is not the swiftUI way...

**Comment by ksemianov** [comment]
Well, if you really need a coordinate level control when placing individual views, you might want to try [SwiftUI Canvas](https://developer.apple.com/documentation/swiftui/canvas).

<img width="506" alt="Screenshot 2024-01-27 at 12 23 31" src="https://github.com/ksemianov/HexGrid/assets/18328341/1446bc60-021e-4bd1-828c-73af5dc3104b">

The screenshot was created with [this gist](https://gist.github.com/ksemianov/826cfc432ce08c594a042206f3df4b56).

**Comment by shinyone** [comment]
Amazing!   Thank you so much!
